"""Report generation endpoints — PRD Section 1.3 (reports).

Generates HTML/PDF/CSV reports for instruments, portfolios, and signals.
"""

import uuid
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.auth import get_current_user
from apps.api.database import get_db
from packages.domain.entities.models import (
    Instrument, Signal, Portfolio, Position, Transaction,
    BacktestRun, MarketBar, User,
)
from packages.domain.enums.common import Timeframe

router = APIRouter(prefix="/reports", tags=["reports"])


# ── Helpers ─────────────────────────────────────────────────

def _html_page(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #0f172a; }}
h1 {{ color: #1e40af; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }}
h2 {{ color: #334155; margin-top: 2rem; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th, td {{ text-align: left; padding: 0.5rem; border-bottom: 1px solid #e2e8f0; font-size: 0.875rem; }}
th {{ background: #f8fafc; font-weight: 600; }}
.positive {{ color: #16a34a; }} .negative {{ color: #dc2626; }}
.badge {{ display: inline-block; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.75rem; }}
.badge-pass {{ background: #dcfce7; color: #16a34a; }}
.badge-warn {{ background: #fef3c7; color: #d97706; }}
.badge-fail {{ background: #fee2e2; color: #dc2626; }}
.footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.75rem; }}
</style></head><body>{body}
<div class="footer">Generated by Market Platform · {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")} · Research only — not financial advice</div>
</body></html>"""


# ── Endpoints ───────────────────────────────────────────────

@router.get("/instrument/{instrument_id}", response_class=HTMLResponse)
async def instrument_report(
    instrument_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    _user: User = Depends(get_current_user),
):
    """Generate an HTML report for an instrument."""
    inst = (await db.execute(select(Instrument).where(Instrument.id == instrument_id))).scalar_one_or_none()
    if not inst:
        raise HTTPException(status_code=404, detail="Instrument not found")

    # Latest bars
    bars_result = await db.execute(
        select(MarketBar)
        .where(MarketBar.instrument_id == instrument_id, MarketBar.timeframe == Timeframe.DAILY)
        .order_by(desc(MarketBar.ts_open))
        .limit(30)
    )
    bars = bars_result.scalars().all()

    # Signals
    sig_result = await db.execute(
        select(Signal).where(Signal.instrument_id == instrument_id).order_by(desc(Signal.created_at)).limit(10)
    )
    signals = sig_result.scalars().all()

    body = f"<h1>{inst.symbol} — {inst.name}</h1>"
    body += f"<p><strong>Type:</strong> {inst.type.value} · <strong>Exchange:</strong> {inst.exchange or '—'} · <strong>Sector:</strong> {inst.sector or '—'}</p>"

    # Price table
    if bars:
        body += "<h2>Recent Prices (30 days)</h2><table><tr><th>Date</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr>"
        for b in bars[:15]:
            body += f"<tr><td>{b.ts_open.strftime('%Y-%m-%d')}</td><td>{b.open}</td><td>{b.high}</td><td>{b.low}</td><td>{b.close}</td><td>{float(b.volume):,.0f}</td></tr>"
        body += "</table>"

    # Signals
    if signals:
        body += "<h2>Recent Signals</h2><table><tr><th>Date</th><th>Strategy</th><th>State</th><th>Confidence</th><th>Quality</th></tr>"
        for s in signals:
            gate_class = "badge-pass" if s.quality_gate.value == "PASS" else "badge-warn" if s.quality_gate.value == "WARN" else "badge-fail"
            body += f"<tr><td>{s.created_at.strftime('%Y-%m-%d')}</td><td>{s.horizon.value}</td><td>{s.state.value}</td><td>{float(s.confidence)*100:.0f}%</td><td><span class='badge {gate_class}'>{s.quality_gate.value}</span></td></tr>"
        body += "</table>"

    return HTMLResponse(_html_page(f"Report: {inst.symbol}", body))


@router.get("/portfolio/{portfolio_id}", response_class=HTMLResponse)
async def portfolio_report(
    portfolio_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate an HTML report for a portfolio."""
    port = (await db.execute(
        select(Portfolio).where(Portfolio.id == portfolio_id, Portfolio.owner_id == current_user.id)
    )).scalar_one_or_none()
    if not port:
        raise HTTPException(status_code=404, detail="Portfolio not found")

    pos_result = await db.execute(select(Position).where(Position.portfolio_id == portfolio_id))
    positions = pos_result.scalars().all()

    body = f"<h1>Portfolio: {port.name}</h1>"
    body += f"<p><strong>Type:</strong> {port.type.value} · <strong>Currency:</strong> {port.base_currency}</p>"

    if positions:
        body += "<h2>Positions</h2><table><tr><th>Symbol</th><th>Qty</th><th>Avg Cost</th><th>Unrealized P&L</th><th>Realized P&L</th></tr>"
        total_pnl = 0
        for pos in positions:
            inst = (await db.execute(select(Instrument).where(Instrument.id == pos.instrument_id))).scalar_one_or_none()
            pnl_class = "positive" if float(pos.unrealized_pnl) >= 0 else "negative"
            body += f"<tr><td>{inst.symbol if inst else '?'}</td><td>{pos.quantity}</td><td>{pos.avg_cost}</td><td class='{pnl_class}'>{pos.unrealized_pnl}</td><td>{pos.realized_pnl}</td></tr>"
            total_pnl += float(pos.unrealized_pnl)
        body += f"</table><p><strong>Total Unrealized P&L:</strong> <span class='{'positive' if total_pnl >= 0 else 'negative'}'>{total_pnl:,.2f}</span></p>"

    return HTMLResponse(_html_page(f"Portfolio: {port.name}", body))
