"""add target_price to signals

Revision ID: 43c3ab91e10f
Revises: 7b4b94733c74
Create Date: 2026-09-03 05:03:48.443565
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '43c3ab91e10f'
down_revision: Union[str, None] = '7b4b94733c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('target_price', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'target_price')
    # ### end Alembic commands ###
